name: Check code smells
on: [push, pull_request]
jobs:
  smell-check:
    name: Smell check
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "manele-se/code-smell-tool@v1.1.5"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
